//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basketball
    {
        public int Id { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
        public Nullable<int> Passed { get; set; }
        public string Venue { get; set; }
        public string PaidCourtId { get; set; }
        public Nullable<decimal> PaidAmmount { get; set; }
    }
}
